Fixed variable naming incosistency that lead to
NameError: undefined local variable or method `expected_build_number' for #<JenkinsApi::Client::Job>
	from /Users/Sebastian/.rvm/gems/ruby-1.9.3-p327/bundler/gems/jenkins_api_client-98d8f27bc0aa/lib/jenkins_api_client/job.rb:919:in `block in get_build_id_the_old_way'

introduced in 94bd8b1 (merged pull request #106)